name = "TI-vreg"
version = "0.2.0"
[dependencies]
# Introduce this once we have stabilized versions
#  Will need setup a path dependency to `power-systems` in the mean time.
#power-systems = { git = "JITx-Inc/power-systems", version = "0.2.0" }
